// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail/v1/mail.proto

package mail

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailResponse_ServingStatus int32

const (
	EmailResponse_SUCCESS     EmailResponse_ServingStatus = 0
	EmailResponse_FAILED      EmailResponse_ServingStatus = 1
	EmailResponse_NOT_SERVING EmailResponse_ServingStatus = 2
)

var EmailResponse_ServingStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
	2: "NOT_SERVING",
}

var EmailResponse_ServingStatus_value = map[string]int32{
	"SUCCESS":     0,
	"FAILED":      1,
	"NOT_SERVING": 2,
}

func (x EmailResponse_ServingStatus) String() string {
	return proto.EnumName(EmailResponse_ServingStatus_name, int32(x))
}

func (EmailResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{0, 0}
}

type EmailResponse struct {
	Status               EmailResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.v1.mail.EmailResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *EmailResponse) Reset()         { *m = EmailResponse{} }
func (m *EmailResponse) String() string { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()    {}
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{0}
}

func (m *EmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResponse.Unmarshal(m, b)
}
func (m *EmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResponse.Marshal(b, m, deterministic)
}
func (m *EmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResponse.Merge(m, src)
}
func (m *EmailResponse) XXX_Size() int {
	return xxx_messageInfo_EmailResponse.Size(m)
}
func (m *EmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResponse proto.InternalMessageInfo

func (m *EmailResponse) GetStatus() EmailResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return EmailResponse_SUCCESS
}

type AccountVerificationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VerificationToken    string   `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountVerificationRequest) Reset()         { *m = AccountVerificationRequest{} }
func (m *AccountVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*AccountVerificationRequest) ProtoMessage()    {}
func (*AccountVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{1}
}

func (m *AccountVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountVerificationRequest.Unmarshal(m, b)
}
func (m *AccountVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountVerificationRequest.Marshal(b, m, deterministic)
}
func (m *AccountVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountVerificationRequest.Merge(m, src)
}
func (m *AccountVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_AccountVerificationRequest.Size(m)
}
func (m *AccountVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountVerificationRequest proto.InternalMessageInfo

func (m *AccountVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccountVerificationRequest) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

type ResetPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PasswordId           string   `protobuf:"bytes,2,opt,name=password_id,json=passwordId,proto3" json:"password_id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{2}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetPasswordId() string {
	if m != nil {
		return m.PasswordId
	}
	return ""
}

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{3}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PaymentRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Payment              []byte   `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{4}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PaymentRequest) GetPayment() []byte {
	if m != nil {
		return m.Payment
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_37fe58669483f1c9, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("api.v1.mail.EmailResponse_ServingStatus", EmailResponse_ServingStatus_name, EmailResponse_ServingStatus_value)
	proto.RegisterType((*EmailResponse)(nil), "api.v1.mail.EmailResponse")
	proto.RegisterType((*AccountVerificationRequest)(nil), "api.v1.mail.AccountVerificationRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "api.v1.mail.ResetPasswordRequest")
	proto.RegisterType((*EmailRequest)(nil), "api.v1.mail.EmailRequest")
	proto.RegisterType((*PaymentRequest)(nil), "api.v1.mail.PaymentRequest")
	proto.RegisterType((*Empty)(nil), "api.v1.mail.Empty")
}

func init() { proto.RegisterFile("mail/v1/mail.proto", fileDescriptor_37fe58669483f1c9) }

var fileDescriptor_37fe58669483f1c9 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0x5a, 0x9a, 0x88, 0x71, 0x5b, 0xd2, 0xa1, 0x12, 0x21, 0x80, 0x80, 0x15, 0x12, 0xbd,
	0xe0, 0xa8, 0xe5, 0xc4, 0xad, 0x25, 0x35, 0x28, 0x52, 0x1b, 0xaa, 0x75, 0xa8, 0x10, 0x97, 0xb0,
	0x38, 0x53, 0x6b, 0x45, 0xb2, 0x6b, 0xbc, 0x9b, 0xa0, 0xfe, 0x03, 0xdf, 0xc4, 0xb7, 0xa1, 0x5d,
	0xbb, 0xc2, 0x16, 0x69, 0x2a, 0xf5, 0x64, 0xcd, 0xcc, 0x7b, 0x6f, 0x9e, 0xe7, 0x69, 0x01, 0x67,
	0x42, 0x4e, 0x7b, 0x8b, 0x83, 0x9e, 0xfb, 0x86, 0x59, 0xae, 0xad, 0xc6, 0x40, 0x64, 0x32, 0x5c,
	0x1c, 0x84, 0xae, 0xd5, 0x7d, 0x9a, 0x6a, 0x9d, 0x4e, 0xa9, 0x27, 0x32, 0xd9, 0x13, 0x4a, 0x69,
	0x2b, 0xac, 0xd4, 0xca, 0x14, 0x50, 0xf6, 0xbb, 0x01, 0xdb, 0x91, 0xc3, 0x71, 0x32, 0x99, 0x56,
	0x86, 0xf0, 0x08, 0x9a, 0xc6, 0x0a, 0x3b, 0x37, 0x9d, 0xc6, 0x8b, 0xc6, 0xfe, 0xce, 0xe1, 0x7e,
	0x58, 0x51, 0x0b, 0x6b, 0xd8, 0x30, 0xa6, 0x7c, 0x21, 0x55, 0x1a, 0x7b, 0x3c, 0x2f, 0x79, 0xec,
	0x1d, 0x6c, 0xd7, 0x06, 0x18, 0x40, 0x2b, 0xfe, 0xdc, 0xef, 0x47, 0x71, 0xdc, 0x5e, 0x43, 0x80,
	0xe6, 0x87, 0xe3, 0xc1, 0x69, 0x74, 0xd2, 0x6e, 0xe0, 0x03, 0x08, 0x86, 0x9f, 0x46, 0xe3, 0x38,
	0xe2, 0x17, 0x83, 0xe1, 0xc7, 0xf6, 0x3a, 0x13, 0xd0, 0x3d, 0x4e, 0x12, 0x3d, 0x57, 0xf6, 0x82,
	0x72, 0x79, 0x29, 0x13, 0x6f, 0x96, 0xd3, 0xcf, 0x39, 0x19, 0x8b, 0x7b, 0xb0, 0x49, 0x6e, 0xbf,
	0x77, 0x76, 0x9f, 0x17, 0x05, 0xbe, 0x01, 0x5c, 0x54, 0xc0, 0x63, 0xab, 0x7f, 0x90, 0xea, 0xac,
	0x7b, 0xc8, 0x6e, 0x75, 0x32, 0x72, 0x03, 0x96, 0xc0, 0x1e, 0x27, 0x43, 0xf6, 0x5c, 0x18, 0xf3,
	0x4b, 0xe7, 0x93, 0x8a, 0x78, 0xc1, 0x2c, 0xc5, 0x7d, 0x81, 0xcf, 0x21, 0xc8, 0x4a, 0xe0, 0x58,
	0x4e, 0x4a, 0x55, 0xb8, 0x6e, 0x0d, 0x26, 0xff, 0x3c, 0x6d, 0x54, 0x3c, 0xb1, 0x57, 0xb0, 0x55,
	0x5e, 0x6a, 0x85, 0x73, 0x76, 0x04, 0x3b, 0xe7, 0xe2, 0x6a, 0x46, 0xca, 0xae, 0xfe, 0xc3, 0x0e,
	0xb4, 0xb2, 0x02, 0xe7, 0x0d, 0x6c, 0xf1, 0xeb, 0x92, 0xb5, 0x60, 0x33, 0x9a, 0x65, 0xf6, 0xea,
	0xf0, 0xcf, 0x06, 0x04, 0x67, 0x42, 0x4e, 0xfd, 0xe1, 0x13, 0xc2, 0x21, 0x3c, 0xe4, 0x94, 0x4a,
	0x63, 0x29, 0x77, 0x6d, 0xa9, 0xd2, 0x53, 0x69, 0x2c, 0x3e, 0x5e, 0x16, 0xa6, 0x5f, 0xdd, 0xed,
	0xde, 0x9c, 0x33, 0x5b, 0xc3, 0x6f, 0xf0, 0x28, 0x26, 0x35, 0x59, 0x12, 0x0e, 0xbe, 0xae, 0x11,
	0x6f, 0x8e, 0xef, 0x96, 0x0d, 0x23, 0xd8, 0x75, 0x1b, 0x6a, 0xd9, 0xe0, 0xcb, 0x1a, 0x65, 0x59,
	0x6e, 0xb7, 0xa8, 0x7e, 0x81, 0x67, 0xff, 0xa9, 0xf6, 0xb5, 0xba, 0x94, 0xf9, 0xac, 0x70, 0x7f,
	0xe7, 0x8b, 0x9c, 0x01, 0x3a, 0xe5, 0x32, 0xc0, 0x13, 0x4a, 0xa6, 0x52, 0x11, 0x3e, 0xa9, 0x71,
	0xea, 0xe9, 0xae, 0x12, 0x7c, 0xdf, 0xfc, 0x7a, 0xcf, 0xd5, 0xdf, 0x9b, 0xfe, 0x5d, 0xbe, 0xfd,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x71, 0xe8, 0xbf, 0x9a, 0xd8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailServiceClient interface {
	RegisterMailingList(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	SendAccountVerification(ctx context.Context, in *AccountVerificationRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	SendResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	SendResetPasswordConfirmation(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
	SendPaymentDecline(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type mailServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailServiceClient(cc *grpc.ClientConn) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) RegisterMailingList(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.mail.MailService/RegisterMailingList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendAccountVerification(ctx context.Context, in *AccountVerificationRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.mail.MailService/SendAccountVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.mail.MailService/SendResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendResetPasswordConfirmation(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.mail.MailService/SendResetPasswordConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendPaymentDecline(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/api.v1.mail.MailService/SendPaymentDecline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
type MailServiceServer interface {
	RegisterMailingList(context.Context, *EmailRequest) (*EmailResponse, error)
	SendAccountVerification(context.Context, *AccountVerificationRequest) (*EmailResponse, error)
	SendResetPassword(context.Context, *ResetPasswordRequest) (*EmailResponse, error)
	SendResetPasswordConfirmation(context.Context, *EmailRequest) (*EmailResponse, error)
	SendPaymentDecline(context.Context, *PaymentRequest) (*EmailResponse, error)
}

// UnimplementedMailServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (*UnimplementedMailServiceServer) RegisterMailingList(ctx context.Context, req *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMailingList not implemented")
}
func (*UnimplementedMailServiceServer) SendAccountVerification(ctx context.Context, req *AccountVerificationRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountVerification not implemented")
}
func (*UnimplementedMailServiceServer) SendResetPassword(ctx context.Context, req *ResetPasswordRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResetPassword not implemented")
}
func (*UnimplementedMailServiceServer) SendResetPasswordConfirmation(ctx context.Context, req *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResetPasswordConfirmation not implemented")
}
func (*UnimplementedMailServiceServer) SendPaymentDecline(ctx context.Context, req *PaymentRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPaymentDecline not implemented")
}

func RegisterMailServiceServer(s *grpc.Server, srv MailServiceServer) {
	s.RegisterService(&_MailService_serviceDesc, srv)
}

func _MailService_RegisterMailingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).RegisterMailingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.mail.MailService/RegisterMailingList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).RegisterMailingList(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendAccountVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendAccountVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.mail.MailService/SendAccountVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendAccountVerification(ctx, req.(*AccountVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.mail.MailService/SendResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendResetPasswordConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendResetPasswordConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.mail.MailService/SendResetPasswordConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendResetPasswordConfirmation(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendPaymentDecline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendPaymentDecline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.mail.MailService/SendPaymentDecline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendPaymentDecline(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.mail.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMailingList",
			Handler:    _MailService_RegisterMailingList_Handler,
		},
		{
			MethodName: "SendAccountVerification",
			Handler:    _MailService_SendAccountVerification_Handler,
		},
		{
			MethodName: "SendResetPassword",
			Handler:    _MailService_SendResetPassword_Handler,
		},
		{
			MethodName: "SendResetPasswordConfirmation",
			Handler:    _MailService_SendResetPasswordConfirmation_Handler,
		},
		{
			MethodName: "SendPaymentDecline",
			Handler:    _MailService_SendPaymentDecline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail/v1/mail.proto",
}
