FROM golang:1.13-alpine

WORKDIR /accounts
COPY go.mod . 
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

# For some reason .dockerignore doesn't work.
COPY . .
COPY ./cmd/grpc_health_probe-linux-amd64 /go/bin/

CMD ["go", "run", "main.go"]
