apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: accounts-go
build:
  artifacts:
  - image: registry.gitlab.com/isaiahwong/cluster/api/accounts
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - k8s/accounts.yaml
