// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1/schema.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Preferences
type Preferences struct {
	Language             string                          `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	EmailNotifications   *Preferences_EmailNotifications `protobuf:"bytes,2,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	PushNotifications    *Preferences_PushNotifications  `protobuf:"bytes,3,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Preferences) Reset()         { *m = Preferences{} }
func (m *Preferences) String() string { return proto.CompactTextString(m) }
func (*Preferences) ProtoMessage()    {}
func (*Preferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{0}
}

func (m *Preferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preferences.Unmarshal(m, b)
}
func (m *Preferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preferences.Marshal(b, m, deterministic)
}
func (m *Preferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preferences.Merge(m, src)
}
func (m *Preferences) XXX_Size() int {
	return xxx_messageInfo_Preferences.Size(m)
}
func (m *Preferences) XXX_DiscardUnknown() {
	xxx_messageInfo_Preferences.DiscardUnknown(m)
}

var xxx_messageInfo_Preferences proto.InternalMessageInfo

func (m *Preferences) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Preferences) GetEmailNotifications() *Preferences_EmailNotifications {
	if m != nil {
		return m.EmailNotifications
	}
	return nil
}

func (m *Preferences) GetPushNotifications() *Preferences_PushNotifications {
	if m != nil {
		return m.PushNotifications
	}
	return nil
}

type Preferences_EmailNotifications struct {
	UnsubscribeFromAll   bool     `protobuf:"varint,1,opt,name=unsubscribe_from_all,json=unsubscribeFromAll,proto3" json:"unsubscribe_from_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preferences_EmailNotifications) Reset()         { *m = Preferences_EmailNotifications{} }
func (m *Preferences_EmailNotifications) String() string { return proto.CompactTextString(m) }
func (*Preferences_EmailNotifications) ProtoMessage()    {}
func (*Preferences_EmailNotifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{0, 0}
}

func (m *Preferences_EmailNotifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preferences_EmailNotifications.Unmarshal(m, b)
}
func (m *Preferences_EmailNotifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preferences_EmailNotifications.Marshal(b, m, deterministic)
}
func (m *Preferences_EmailNotifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preferences_EmailNotifications.Merge(m, src)
}
func (m *Preferences_EmailNotifications) XXX_Size() int {
	return xxx_messageInfo_Preferences_EmailNotifications.Size(m)
}
func (m *Preferences_EmailNotifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Preferences_EmailNotifications.DiscardUnknown(m)
}

var xxx_messageInfo_Preferences_EmailNotifications proto.InternalMessageInfo

func (m *Preferences_EmailNotifications) GetUnsubscribeFromAll() bool {
	if m != nil {
		return m.UnsubscribeFromAll
	}
	return false
}

type Preferences_PushNotifications struct {
	UnsubscribeFromAll   bool     `protobuf:"varint,1,opt,name=unsubscribe_from_all,json=unsubscribeFromAll,proto3" json:"unsubscribe_from_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preferences_PushNotifications) Reset()         { *m = Preferences_PushNotifications{} }
func (m *Preferences_PushNotifications) String() string { return proto.CompactTextString(m) }
func (*Preferences_PushNotifications) ProtoMessage()    {}
func (*Preferences_PushNotifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{0, 1}
}

func (m *Preferences_PushNotifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preferences_PushNotifications.Unmarshal(m, b)
}
func (m *Preferences_PushNotifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preferences_PushNotifications.Marshal(b, m, deterministic)
}
func (m *Preferences_PushNotifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preferences_PushNotifications.Merge(m, src)
}
func (m *Preferences_PushNotifications) XXX_Size() int {
	return xxx_messageInfo_Preferences_PushNotifications.Size(m)
}
func (m *Preferences_PushNotifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Preferences_PushNotifications.DiscardUnknown(m)
}

var xxx_messageInfo_Preferences_PushNotifications proto.InternalMessageInfo

func (m *Preferences_PushNotifications) GetUnsubscribeFromAll() bool {
	if m != nil {
		return m.UnsubscribeFromAll
	}
	return false
}

type ProfileName struct {
	FamilyName           string   `protobuf:"bytes,1,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,2,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileName) Reset()         { *m = ProfileName{} }
func (m *ProfileName) String() string { return proto.CompactTextString(m) }
func (*ProfileName) ProtoMessage()    {}
func (*ProfileName) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{1}
}

func (m *ProfileName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileName.Unmarshal(m, b)
}
func (m *ProfileName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileName.Marshal(b, m, deterministic)
}
func (m *ProfileName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileName.Merge(m, src)
}
func (m *ProfileName) XXX_Size() int {
	return xxx_messageInfo_ProfileName.Size(m)
}
func (m *ProfileName) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileName.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileName proto.InternalMessageInfo

func (m *ProfileName) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *ProfileName) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *ProfileName) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

type ProfileEmails struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileEmails) Reset()         { *m = ProfileEmails{} }
func (m *ProfileEmails) String() string { return proto.CompactTextString(m) }
func (*ProfileEmails) ProtoMessage()    {}
func (*ProfileEmails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{2}
}

func (m *ProfileEmails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileEmails.Unmarshal(m, b)
}
func (m *ProfileEmails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileEmails.Marshal(b, m, deterministic)
}
func (m *ProfileEmails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileEmails.Merge(m, src)
}
func (m *ProfileEmails) XXX_Size() int {
	return xxx_messageInfo_ProfileEmails.Size(m)
}
func (m *ProfileEmails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileEmails.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileEmails proto.InternalMessageInfo

func (m *ProfileEmails) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ProfileEmails) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ProfilePhotos struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePhotos) Reset()         { *m = ProfilePhotos{} }
func (m *ProfilePhotos) String() string { return proto.CompactTextString(m) }
func (*ProfilePhotos) ProtoMessage()    {}
func (*ProfilePhotos) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{3}
}

func (m *ProfilePhotos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePhotos.Unmarshal(m, b)
}
func (m *ProfilePhotos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePhotos.Marshal(b, m, deterministic)
}
func (m *ProfilePhotos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePhotos.Merge(m, src)
}
func (m *ProfilePhotos) XXX_Size() int {
	return xxx_messageInfo_ProfilePhotos.Size(m)
}
func (m *ProfilePhotos) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePhotos.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePhotos proto.InternalMessageInfo

func (m *ProfilePhotos) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserProfileFacebook struct {
	Provider             string           `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id                   string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string           `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Name                 *ProfileName     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Emails               []*ProfileEmails `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Photos               []*ProfilePhotos `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserProfileFacebook) Reset()         { *m = UserProfileFacebook{} }
func (m *UserProfileFacebook) String() string { return proto.CompactTextString(m) }
func (*UserProfileFacebook) ProtoMessage()    {}
func (*UserProfileFacebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{4}
}

func (m *UserProfileFacebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileFacebook.Unmarshal(m, b)
}
func (m *UserProfileFacebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileFacebook.Marshal(b, m, deterministic)
}
func (m *UserProfileFacebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileFacebook.Merge(m, src)
}
func (m *UserProfileFacebook) XXX_Size() int {
	return xxx_messageInfo_UserProfileFacebook.Size(m)
}
func (m *UserProfileFacebook) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileFacebook.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileFacebook proto.InternalMessageInfo

func (m *UserProfileFacebook) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *UserProfileFacebook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfileFacebook) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserProfileFacebook) GetName() *ProfileName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UserProfileFacebook) GetEmails() []*ProfileEmails {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UserProfileFacebook) GetPhotos() []*ProfilePhotos {
	if m != nil {
		return m.Photos
	}
	return nil
}

type UserProfileGoogle struct {
	Provider             string           `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id                   string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string           `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Name                 *ProfileName     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Emails               []*ProfileEmails `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Photos               []*ProfilePhotos `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserProfileGoogle) Reset()         { *m = UserProfileGoogle{} }
func (m *UserProfileGoogle) String() string { return proto.CompactTextString(m) }
func (*UserProfileGoogle) ProtoMessage()    {}
func (*UserProfileGoogle) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{5}
}

func (m *UserProfileGoogle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileGoogle.Unmarshal(m, b)
}
func (m *UserProfileGoogle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileGoogle.Marshal(b, m, deterministic)
}
func (m *UserProfileGoogle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileGoogle.Merge(m, src)
}
func (m *UserProfileGoogle) XXX_Size() int {
	return xxx_messageInfo_UserProfileGoogle.Size(m)
}
func (m *UserProfileGoogle) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileGoogle.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileGoogle proto.InternalMessageInfo

func (m *UserProfileGoogle) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *UserProfileGoogle) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfileGoogle) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserProfileGoogle) GetName() *ProfileName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UserProfileGoogle) GetEmails() []*ProfileEmails {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UserProfileGoogle) GetPhotos() []*ProfilePhotos {
	if m != nil {
		return m.Photos
	}
	return nil
}

type Auth struct {
	Facebook                 *UserProfileFacebook `protobuf:"bytes,1,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Google                   *UserProfileGoogle   `protobuf:"bytes,2,opt,name=google,proto3" json:"google,omitempty"`
	Email                    string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Firstname                string               `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname                 string               `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Name                     string               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Picture                  string               `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	Password                 string               `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	PasswordHashMethod       string               `protobuf:"bytes,9,opt,name=password_hash_method,json=passwordHashMethod,proto3" json:"password_hash_method,omitempty"`
	PasswordId               string               `protobuf:"bytes,10,opt,name=password_id,json=passwordId,proto3" json:"password_id,omitempty"`
	PasswordResetToken       string               `protobuf:"bytes,11,opt,name=password_reset_token,json=passwordResetToken,proto3" json:"password_reset_token,omitempty"`
	PasswordResetExpires     int32                `protobuf:"varint,12,opt,name=password_reset_expires,json=passwordResetExpires,proto3" json:"password_reset_expires,omitempty"`
	PasswordModified         int32                `protobuf:"varint,13,opt,name=password_modified,json=passwordModified,proto3" json:"password_modified,omitempty"`
	Verified                 bool                 `protobuf:"varint,14,opt,name=verified,proto3" json:"verified,omitempty"`
	VerifiedDate             int32                `protobuf:"varint,15,opt,name=verified_date,json=verifiedDate,proto3" json:"verified_date,omitempty"`
	VerificationToken        string               `protobuf:"bytes,16,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	VerificationTokenExpires int32                `protobuf:"varint,17,opt,name=verification_token_expires,json=verificationTokenExpires,proto3" json:"verification_token_expires,omitempty"`
	CaptchaChallengeTs       int32                `protobuf:"varint,18,opt,name=captcha_challenge_ts,json=captchaChallengeTs,proto3" json:"captcha_challenge_ts,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}             `json:"-"`
	XXX_unrecognized         []byte               `json:"-"`
	XXX_sizecache            int32                `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{6}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetFacebook() *UserProfileFacebook {
	if m != nil {
		return m.Facebook
	}
	return nil
}

func (m *Auth) GetGoogle() *UserProfileGoogle {
	if m != nil {
		return m.Google
	}
	return nil
}

func (m *Auth) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Auth) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Auth) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Auth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Auth) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Auth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Auth) GetPasswordHashMethod() string {
	if m != nil {
		return m.PasswordHashMethod
	}
	return ""
}

func (m *Auth) GetPasswordId() string {
	if m != nil {
		return m.PasswordId
	}
	return ""
}

func (m *Auth) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

func (m *Auth) GetPasswordResetExpires() int32 {
	if m != nil {
		return m.PasswordResetExpires
	}
	return 0
}

func (m *Auth) GetPasswordModified() int32 {
	if m != nil {
		return m.PasswordModified
	}
	return 0
}

func (m *Auth) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Auth) GetVerifiedDate() int32 {
	if m != nil {
		return m.VerifiedDate
	}
	return 0
}

func (m *Auth) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

func (m *Auth) GetVerificationTokenExpires() int32 {
	if m != nil {
		return m.VerificationTokenExpires
	}
	return 0
}

func (m *Auth) GetCaptchaChallengeTs() int32 {
	if m != nil {
		return m.CaptchaChallengeTs
	}
	return 0
}

type User struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               string       `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Auth                 *Auth        `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Preferences          *Preferences `protobuf:"bytes,4,opt,name=preferences,proto3" json:"preferences,omitempty"`
	CreatedAt            int32        `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int32        `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LoggedIn             int32        `protobuf:"varint,7,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	LoggedInIp           string       `protobuf:"bytes,8,opt,name=logged_in_ip,json=loggedInIp,proto3" json:"logged_in_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b326282f43c30d45, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *User) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *User) GetPreferences() *Preferences {
	if m != nil {
		return m.Preferences
	}
	return nil
}

func (m *User) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetLoggedIn() int32 {
	if m != nil {
		return m.LoggedIn
	}
	return 0
}

func (m *User) GetLoggedInIp() string {
	if m != nil {
		return m.LoggedInIp
	}
	return ""
}

func init() {
	proto.RegisterType((*Preferences)(nil), "api.v1.auth.Preferences")
	proto.RegisterType((*Preferences_EmailNotifications)(nil), "api.v1.auth.Preferences.EmailNotifications")
	proto.RegisterType((*Preferences_PushNotifications)(nil), "api.v1.auth.Preferences.PushNotifications")
	proto.RegisterType((*ProfileName)(nil), "api.v1.auth.ProfileName")
	proto.RegisterType((*ProfileEmails)(nil), "api.v1.auth.ProfileEmails")
	proto.RegisterType((*ProfilePhotos)(nil), "api.v1.auth.ProfilePhotos")
	proto.RegisterType((*UserProfileFacebook)(nil), "api.v1.auth.UserProfileFacebook")
	proto.RegisterType((*UserProfileGoogle)(nil), "api.v1.auth.UserProfileGoogle")
	proto.RegisterType((*Auth)(nil), "api.v1.auth.Auth")
	proto.RegisterType((*User)(nil), "api.v1.auth.User")
}

func init() { proto.RegisterFile("auth/v1/schema.proto", fileDescriptor_b326282f43c30d45) }

var fileDescriptor_b326282f43c30d45 = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xdf, 0x8f, 0xdb, 0x44,
	0x10, 0x56, 0x72, 0x49, 0x9a, 0x8c, 0xef, 0x4a, 0xb3, 0x8d, 0x2a, 0x2b, 0xfc, 0x0a, 0x41, 0x95,
	0x4e, 0x14, 0xd2, 0xf6, 0x40, 0x48, 0xa0, 0xbe, 0x1c, 0x70, 0x07, 0xf7, 0xd0, 0xea, 0x64, 0x95,
	0x07, 0x10, 0x92, 0xb5, 0xb1, 0x27, 0xf1, 0x52, 0xdb, 0x6b, 0x79, 0xd7, 0x81, 0xfb, 0x27, 0xf8,
	0x13, 0xf9, 0x1f, 0x78, 0x43, 0x3c, 0xa1, 0x9d, 0xdd, 0x75, 0x93, 0xcb, 0xe5, 0x81, 0x67, 0xde,
	0x3c, 0xdf, 0x37, 0xdf, 0x6c, 0x66, 0xfc, 0xcd, 0x3a, 0x30, 0xe1, 0x8d, 0xce, 0x9e, 0x6e, 0x9e,
	0x3f, 0x55, 0x49, 0x86, 0x05, 0x5f, 0x54, 0xb5, 0xd4, 0x92, 0x05, 0xbc, 0x12, 0x8b, 0xcd, 0xf3,
	0x85, 0x21, 0xe7, 0x7f, 0x75, 0x21, 0xb8, 0xae, 0x71, 0x85, 0x35, 0x96, 0x09, 0x2a, 0x36, 0x85,
	0x61, 0xce, 0xcb, 0x75, 0xc3, 0xd7, 0x18, 0x76, 0x66, 0x9d, 0xd3, 0x51, 0xd4, 0xc6, 0xec, 0x17,
	0x78, 0x88, 0x05, 0x17, 0x79, 0x5c, 0x4a, 0x2d, 0x56, 0x22, 0xe1, 0x5a, 0xc8, 0x52, 0x85, 0xdd,
	0x59, 0xe7, 0x34, 0x38, 0x7b, 0xb2, 0xd8, 0x2a, 0xbb, 0xd8, 0x2a, 0xb9, 0xb8, 0x30, 0x9a, 0x57,
	0xdb, 0x92, 0x88, 0xe1, 0x1e, 0xc6, 0x7e, 0x02, 0x56, 0x35, 0x2a, 0xbb, 0x55, 0xfc, 0x88, 0x8a,
	0x7f, 0x72, 0xb0, 0xf8, 0x75, 0xa3, 0xb2, 0xdd, 0xda, 0xe3, 0xea, 0x36, 0x34, 0xbd, 0x04, 0xb6,
	0xff, 0x23, 0xd8, 0x33, 0x98, 0x34, 0xa5, 0x6a, 0x96, 0x2a, 0xa9, 0xc5, 0x12, 0xe3, 0x55, 0x2d,
	0x8b, 0x98, 0xe7, 0x39, 0xb5, 0x3d, 0x8c, 0xd8, 0x16, 0x77, 0x59, 0xcb, 0xe2, 0x3c, 0xcf, 0xa7,
	0x17, 0x30, 0xde, 0x3b, 0xef, 0xbf, 0x97, 0x99, 0x97, 0x66, 0xe4, 0x72, 0x25, 0x72, 0x7c, 0xc5,
	0x0b, 0x64, 0x1f, 0x42, 0xb0, 0xe2, 0x85, 0xc8, 0x6f, 0xe2, 0x92, 0x17, 0x7e, 0xea, 0x60, 0x21,
	0x4a, 0x78, 0x1f, 0x60, 0x2d, 0x36, 0x58, 0x5a, 0xbe, 0x4b, 0xfc, 0x88, 0x10, 0xaf, 0x2f, 0x44,
	0x9a, 0xe6, 0x68, 0xf9, 0x23, 0xab, 0xb7, 0x90, 0x49, 0x98, 0x7f, 0x05, 0x27, 0xee, 0x3c, 0x9a,
	0x82, 0x62, 0x13, 0xe8, 0x6f, 0x78, 0xde, 0xf8, 0xb3, 0x6c, 0xc0, 0x18, 0xf4, 0xf4, 0x4d, 0xe5,
	0x0f, 0xa0, 0xe7, 0xf9, 0xe3, 0x56, 0x7a, 0x9d, 0x49, 0x2d, 0x0f, 0x48, 0xe7, 0xff, 0x74, 0xe0,
	0xe1, 0x8f, 0x0a, 0x6b, 0x97, 0x7b, 0xc9, 0x13, 0x5c, 0x4a, 0xf9, 0xc6, 0xb8, 0xa9, 0xaa, 0xe5,
	0x46, 0xa4, 0x58, 0x7b, 0x37, 0xf9, 0x98, 0xdd, 0x87, 0xae, 0x48, 0xdd, 0x61, 0x5d, 0x91, 0xb2,
	0x8f, 0xe0, 0x38, 0x15, 0xaa, 0xca, 0xf9, 0xcd, 0x76, 0x1f, 0x81, 0xc3, 0xa8, 0xd3, 0x4f, 0xa1,
	0x47, 0x54, 0x8f, 0x4c, 0x11, 0xde, 0x32, 0x45, 0x3b, 0xd1, 0x88, 0xb2, 0xd8, 0x19, 0x0c, 0xc8,
	0x66, 0x2a, 0xec, 0xcf, 0x8e, 0x4e, 0x83, 0xb3, 0xe9, 0x5d, 0xf9, 0x76, 0x22, 0x91, 0xcb, 0x34,
	0x9a, 0x8a, 0x1a, 0x0d, 0x07, 0x87, 0x35, 0x76, 0x14, 0x91, 0xcb, 0x9c, 0xff, 0xdd, 0x81, 0xf1,
	0x56, 0xf3, 0xdf, 0x4b, 0xb9, 0xce, 0xf1, 0xff, 0xd1, 0xfa, 0x9f, 0x7d, 0xe8, 0x9d, 0x37, 0x3a,
	0x63, 0x2f, 0x60, 0xb8, 0x72, 0x2f, 0x9d, 0xba, 0x0d, 0xce, 0x66, 0x3b, 0xf2, 0x3b, 0xcc, 0x11,
	0xb5, 0x0a, 0xf6, 0x25, 0x0c, 0xd6, 0x34, 0x35, 0x77, 0x97, 0x7c, 0x70, 0x48, 0x6b, 0x67, 0x1b,
	0xb9, 0x6c, 0x63, 0x46, 0xfa, 0xf1, 0x6e, 0x60, 0x36, 0x60, 0xef, 0xc1, 0x68, 0x25, 0x6a, 0xa5,
	0xdb, 0x79, 0x8d, 0xa2, 0xb7, 0x80, 0xbd, 0xe0, 0x1c, 0xd9, 0xf7, 0x17, 0x9c, 0xe3, 0x98, 0x1b,
	0xf2, 0xc0, 0x6e, 0x00, 0x61, 0x21, 0xdc, 0xab, 0x44, 0xa2, 0x9b, 0x1a, 0xc3, 0x7b, 0x04, 0xfb,
	0x90, 0xde, 0x30, 0x57, 0xea, 0x37, 0x59, 0xa7, 0xe1, 0xd0, 0xbd, 0x61, 0x17, 0x9b, 0x4b, 0xc1,
	0x3f, 0xc7, 0x19, 0x57, 0x59, 0x5c, 0xa0, 0xce, 0x64, 0x1a, 0x8e, 0x28, 0x8f, 0x79, 0xee, 0x07,
	0xae, 0xb2, 0x97, 0xc4, 0x98, 0x2d, 0x6e, 0x15, 0x22, 0x0d, 0xc1, 0x6e, 0xb1, 0x87, 0xae, 0x76,
	0x4b, 0xd6, 0xa8, 0x50, 0xc7, 0x5a, 0xbe, 0xc1, 0x32, 0x0c, 0x76, 0x4b, 0x46, 0x86, 0x7a, 0x6d,
	0x18, 0xf6, 0x05, 0x3c, 0xba, 0xa5, 0xc0, 0xdf, 0x2b, 0x51, 0xa3, 0x0a, 0x8f, 0x67, 0x9d, 0xd3,
	0x7e, 0x34, 0xd9, 0xd1, 0x5c, 0x58, 0x8e, 0x3d, 0x81, 0x71, 0xab, 0x2a, 0x64, 0x2a, 0x56, 0x02,
	0xd3, 0xf0, 0x84, 0x04, 0x0f, 0x3c, 0xf1, 0xd2, 0xe1, 0x66, 0x06, 0x1b, 0xac, 0x6d, 0xce, 0x7d,
	0xba, 0xf0, 0xda, 0x98, 0x7d, 0x0c, 0x27, 0xfe, 0x39, 0x4e, 0xb9, 0xc6, 0xf0, 0x1d, 0x2a, 0x72,
	0xec, 0xc1, 0xef, 0xb8, 0x46, 0xf6, 0x19, 0x30, 0x1b, 0xdb, 0xeb, 0xd4, 0xf5, 0xf4, 0x80, 0x7a,
	0x1a, 0x6f, 0x33, 0xb6, 0xa5, 0x17, 0x30, 0xdd, 0x4f, 0x6f, 0xdb, 0x1a, 0xd3, 0x01, 0xe1, 0x9e,
	0xcc, 0xb7, 0xf6, 0x0c, 0x26, 0x09, 0xaf, 0x74, 0x92, 0xf1, 0x38, 0xc9, 0x78, 0x9e, 0x63, 0xb9,
	0xc6, 0x58, 0xab, 0x90, 0x91, 0x8e, 0x39, 0xee, 0x5b, 0x4f, 0xbd, 0x56, 0xf3, 0x3f, 0xba, 0xd0,
	0x33, 0xfe, 0x73, 0x2b, 0xdb, 0x69, 0x57, 0xf6, 0x11, 0x0c, 0xe4, 0xf2, 0x57, 0x4c, 0xb4, 0x5b,
	0x63, 0x17, 0xb1, 0xc7, 0xd0, 0x33, 0xa6, 0x75, 0xdf, 0xad, 0xf1, 0x8e, 0x91, 0xcd, 0xa6, 0x44,
	0x44, 0xb3, 0xaf, 0x21, 0xa8, 0xde, 0x7e, 0xc5, 0x0e, 0x6c, 0x75, 0xcb, 0x47, 0xdb, 0xc9, 0xe6,
	0x73, 0x90, 0xd4, 0xc8, 0x35, 0xa6, 0x31, 0xd7, 0xe4, 0xe1, 0x7e, 0x34, 0x72, 0xc8, 0xb9, 0x36,
	0x74, 0x53, 0xa5, 0x9e, 0x1e, 0x58, 0xda, 0x21, 0xe7, 0x9a, 0xbd, 0x0b, 0xa3, 0x5c, 0xae, 0xd7,
	0x98, 0xc6, 0xa2, 0x24, 0x47, 0xf7, 0xa3, 0xa1, 0x05, 0xae, 0x4a, 0x36, 0x83, 0xe3, 0x96, 0x8c,
	0x45, 0xe5, 0x6c, 0x0d, 0x9e, 0xbf, 0xaa, 0xbe, 0x19, 0xfc, 0x4c, 0x0d, 0x2c, 0x07, 0xf4, 0x5f,
	0xe2, 0xf3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x11, 0x50, 0xe9, 0xd0, 0x63, 0x08, 0x00, 0x00,
}
