apiVersion: v1
kind: Service
metadata:
  name: api-accounts-v1-accountsservice
  labels:
    resourceType: api-service
  annotations:
    config: '{
      "expose": false,
      "path": "/accounts",
      "apiVersion": "v1"
    }'
spec:
  ports:
  - name: grpc
    port: 5000
    targetPort: accounts-port
  selector: 
    app: accounts
  type: ClusterIP
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-env-configmap
data:
  APP_ENV: "development"
  MAINTENANCE_MODE: "false"
  ADDRESS: ":5000"
  
  # Logging
  ENABLE_STACKDRIVER: "false"
  ENABLE_CONSOLE_LOGS_IN_TEST: "true"

  # Database
  DB_URI: "mongodb://mongo-accounts-service:27017"

  DB_NAME: "accounts"
  DB_TIMEOUT: "60"
  DB_INITIAL_TIMEOUT: "60"

  # Password reset parameters
  PASSWORD_RESET_EXPIRES: "1800000" # in milliseconds

  # Recaptcha
  GOOGLE_RECAPTCHA_URL: "https://www.google.com/recaptcha/api/siteverify"

  # Hydra
  HYDRA_ADMIN_URL: "http://hydra-service.default.svc.cluster.local:9001"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: accounts
  template: 
    metadata: 
      labels: 
        app: accounts
    spec:
      containers:
        - name: accounts
          image: registry.gitlab.com/isaiahwong/cluster/api/accounts
          imagePullPolicy: IfNotPresent
          ports:
          - name: accounts-port
            containerPort: 5000

          # resources:
          #   requests:
          #     cpu: 50m
          #     memory: 64Mi
          #   limits:
          #     cpu: 80m
          #     memory: 128Mi

          # readinessProbe:
          #   exec:
          #     command: ["go/bin/grpc_health_probe-linux-amd64", "-addr=:5000"]
          #   initialDelaySeconds: 5

          livenessProbe:
            exec:
              command: ["/go/bin/grpc_health_probe-linux-amd64", "-addr=:5000"]
            initialDelaySeconds: 60
            
          envFrom:
          - configMapRef:
              name: accounts-env-configmap
          - secretRef:
              name: accounts-env-secrets
              
      imagePullSecrets:
      - name: gitlab-auth

