apiVersion: v1
kind: Service
metadata:
  name: api-accounts-v1-accountsservice
  labels:
    resourceType: api-service
  annotations:
    config: '{
      "expose": true,
      "path": "/accounts",
      "apiVersion": "v1",
      "authentication": {
        "required": "false"
      }
    }'
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: accounts-port
  selector: 
    app: accounts
  type: ClusterIP
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-env-configmap
data:
  NODE_ENV: "development"
  PORT: "5000"
  MAINTENANCE_MODE: "false"
  GRPC_PORT: "5001"
  
  # Logging
  ENABLE_STACKDRIVER: "false"
  ENABLE_CONSOLE_LOGS_IN_TEST: "true"

  # Database
  DB_URI: "mongodb://mongo-accounts-service:27017/"
  DB_URI_DEV: "mongodb://mongo-accounts-service:27017/"
  DB_URI_TEST: "mongodb://mongo-accounts-service:27017/"
  DB_NAME: "accounts"
  DB_TIMEOUT: "60"

  # Password reset parameters
  PASSWORD_RESET_EXPIRES: "1800000" # in milliseconds
  
  # cors
  DEV_CLIENT: "http://localhost:3000"

  # Services
  MAX_RETRIES: "30"
  RETRY_DURATION: "3000"
  
  MAIL_SERVICE_DEV: "mail-service:50051"
  MAIL_SERVICE: "mail-service:50051"

  PAYMENT_SERVICE: "payment-service:50051"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: accounts
  template: 
    metadata: 
      labels: 
        app: accounts
    spec:
      containers:
        - name: accounts
          image: registry.gitlab.com/isaiahwong/api/accounts
          imagePullPolicy: IfNotPresent
          ports:
          - name: accounts-port
            containerPort: 50051

          # resources:
          #   requests:
          #     cpu: 50m
          #     memory: 64Mi
          #   limits:
          #     cpu: 80m
          #     memory: 128Mi

          # readinessProbe:
          #   httpGet:
          #     path: /hz
          #     port: 5000
          #   initialDelaySeconds: 10
          #   periodSeconds: 4
          
          # livenessProbe:
          #   httpGet:
          #     path: /hz
          #     port: 5000
          #   initialDelaySeconds: 60
          #   periodSeconds: 120
            
          envFrom:
          - configMapRef:
              name: accounts-env-configmap
          - secretRef:
              name: mongo-accounts-env-secrets
              
      imagePullSecrets:
      - name: gitlab-auth
