apiVersion: v1
kind: Service
metadata:
  name: hydra-service
spec:
  ports:
  - name: hydra-public-port
    port: 9000
    targetPort: public-port
  - name: hydra-admin-port
    port: 9001
    targetPort: admin-port
  selector: 
    component: hydra
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: hydra
  template:
    metadata:
      labels:
        component: hydra
    spec:
      # initContainers:
      # - name: hydra-sql-migration
      #   image: oryd/hydra:v1.3.2
      #   command: ['hydra', 'migrate', 'sql', '--yes' , '$(DSN)']
      #   envFrom:
      #     - secretRef:
      #         name: accounts-env-secrets
      containers:
        - name: hydra
          image: oryd/hydra:v1.3.2-alpine
          command: ["/bin/sh","-c"]
          args: ["hydra migrate sql --yes $(DSN) && hydra serve all --dangerous-force-http"]
          ports:
            - name: public-port
              containerPort: 4444
            - name: admin-port
              containerPort: 4445
          envFrom:
          - configMapRef:
              name: hydra-config
          - secretRef:
              name: accounts-env-secrets

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
  namespace: default
data:
  URLS_SELF_ISSUER: "https://accounts.isaiahwong.dev/issuer"
  URLS_CONSENT: "https://accounts.isaiahwong.dev/auth/consent/challenge"
  URLS_LOGIN: "https://accounts.isaiahwong.dev/auth/login/challenge"
  URLS_LOGOUT: "https://accounts.isaiahwong.dev/auth/logout"
  URLS_ERROR: "https://accounts.isaiahwong.dev/auth/notfound"
  URLS_POST_LOGOUT_REDIRECT: "https://accounts.isaiahwong.dev/auth/logout"
  SERVE_COOKIES_SAME_SITE_MODE: "Lax"