apiVersion: v1
kind: Service
metadata:
  name: hydra-postgres-service
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: postgres-port
  selector: 
    component: hydra-postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-postgres-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: hydra-postgres
  template:
    metadata:
      labels:
        component: hydra-postgres
    spec:
      containers:
        - name: hydra-postgres
          image: postgres:9.6
          ports:
            - name: postgres-port
              containerPort: 5432
          volumeMounts:
            - name: hydra-postgres-storage
              mountPath: /var/lib/postgresql/data
          envFrom:
          - secretRef:
              name: accounts-env-secrets
          env:
          - name: POSTGRES_DB
            value: "hydra"
          
      volumes:
        - name: hydra-postgres-storage
          persistentVolumeClaim:
            claimName: hydra-postgres-pvc

---

# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra-postgres-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
